version: "3.9"
services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flydb
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flydb
      POSTGRES_HOST: db
    volumes:
      - .:/app

volumes:
  db_data:
